[package]
name = "foundry-fork-db"
description = "Fork database used by Foundry"
version = "0.18.0"
edition = "2021"
# Remember to update clippy.toml as well
rust-version = "1.88"
authors = ["Foundry Contributors", "Seismic Systems"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/SeismicSystems/seismic-foundry-fork-db"
repository = "https://github.com/SeismicSystems/seismic-foundry-fork-db"

[lints]
rust.unused_must_use = "deny"
rust.rust_2018_idioms = { level = "deny", priority = -1 }
rustdoc.all = "warn"

[lints.clippy]
missing_const_for_fn = "allow" # TODO: https://github.com/rust-lang/rust-clippy/issues/14020
use_self = "warn"
option_if_let_else = "warn"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
alloy-chains = { version = "0.2", default-features = false, features = ["serde"] }
alloy-consensus = { version = "1.0.25", default-features = false }
alloy-hardforks = { version = "0.2.13", default-features = false }
alloy-primitives = { version = "1.3", features = ["map"] }
alloy-provider = { version = "1.0.25", default-features = false }
alloy-rpc-types = { version = "1.0.25", features = ["eth"] }

eyre = "0.6"
futures = "0.3"

parking_lot = "0.12"

revm = { version = "29.0.0", features = ["std", "serde"] }

serde = "1.0"
serde_json = "1.0"

thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0.1"

url = "2"

# seismic-prelude is only used for a few things, yet it brings with it a huge dependency chain including enclave,
# which is why we need to patch enclave below.
# TODO(samlaf): We might want to only depend on the exact dependency, or else add feature flags to seismic-prelude.
seismic-prelude = "0.0.1"

[dev-dependencies]
alloy-rpc-client = "1.0.25"
tiny_http = "0.12"

[patch.crates-io]
# seismic-alloy-core
alloy-dyn-abi = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "fa63d477d6aa01e7203b677632c31cb3eba00640" }
alloy-json-abi = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "fa63d477d6aa01e7203b677632c31cb3eba00640" }
alloy-primitives = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "fa63d477d6aa01e7203b677632c31cb3eba00640" }
alloy-sol-macro = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "fa63d477d6aa01e7203b677632c31cb3eba00640" }
alloy-sol-macro-expander = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "fa63d477d6aa01e7203b677632c31cb3eba00640" }
alloy-sol-macro-input = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "fa63d477d6aa01e7203b677632c31cb3eba00640" }
alloy-sol-types = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "fa63d477d6aa01e7203b677632c31cb3eba00640" }
alloy-sol-type-parser = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "fa63d477d6aa01e7203b677632c31cb3eba00640" }

# This is needed because alloy-consensus depends on this crate for some proc macro, and the versions aren't locked together.
# seismic-prelude -> alloy-consensus (=1.1.0 in alloy's Cargo.toml) -> alloy-tx-macros (floating version which didnt respect semver)
alloy-tx-macros = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }

# seismic-revm
revm = { git = "https://github.com/SeismicSystems/seismic-revm.git", rev = "e2ab654c4f8bc5e8f98d15ffe7a9880ace2f8a56" }
seismic-revm = { git = "https://github.com/SeismicSystems/seismic-revm.git", rev = "e2ab654c4f8bc5e8f98d15ffe7a9880ace2f8a56" }

# seismic-alloy
seismic-prelude = { git = "https://github.com/SeismicSystems/seismic-alloy.git", rev = "ebc3628c9e384b1db5a41044dd32756b3e79aacb" }

# seismic-foundry
seismic-enclave = { git = "https://github.com/SeismicSystems/enclave.git", rev = "ac5e28dac1ee8ec0e3922b010e6da072d6e784aa" }
